name: release

on:
  release:
    types:
      - released

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: rustup update stable
    - name: Build and publish
      run: |
        cargo login ${{ secrets.CRATESIO_TOKEN }}
        cargo publish
